apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-storage
  namespace: padungsilpa-group # Match with namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi