apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: padungsilpa-group # Match with namespace
spec:
  type: ClusterIP
  ports:
  - port: 80 # Port that allow nginx to communicate
    targetPort: 80 # Match with MARK C.1
    protocol: TCP
  selector:
    app: wordpress # Match with MARK C