apiVersion: v1
kind: Service
metadata:
  name: http-proxy-service
  namespace: http-proxy-ns # Match with namespace
spec:
  type: ClusterIP
  ports:
  - port: 80 # Port that allow nginx to communicate
    targetPort: 5000 # Match with MARK C.1
    protocol: TCP
  selector:
    app: http-proxy # Match with MARK C